FROM golang:1.23.3 AS builder

WORKDIR /app

# 必要なファイルをコピー
COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/ .

# 本番用ビルド
RUN go build -tags netgo -ldflags '-s -w' -o app

# 実行環境
FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/app .
EXPOSE 8080
CMD ["./app"]