FROM node:23 AS builder

WORKDIR /app

# 必要なファイルをコピーして依存関係をインストール
COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

# 静的ファイルを生成
RUN npm run build

# 実行環境
FROM nginx:alpine
COPY --from=builder /app/out /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]